"""Metrics collection and agent registry tracking

This module keeps three simple in-memory metrics for the running SDK process:
- agent.registration.success.total: counts times the SDK was started with an agent id
- agent.metrics.last_received.timestamp: epoch seconds of the last LLM call
- agent.audit.events.total: total audit events (LLM calls) recorded

Metrics are recorded in-memory and are also emitted via an OpenTelemetry Meter
(using a ConsoleMetricExporter by default). This is purposely simple and
single-process: it provides quick local observability for development and
debugging.
"""

import json
import logging
import time
import atexit
from opentelemetry import metrics
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import ConsoleMetricExporter, PeriodicExportingMetricReader
from opentelemetry.sdk.resources import Resource

logger = logging.getLogger(__name__)

OUTPUT_FORMAT = "console"  # can be 'console' or 'json'

# Simple agent registry state
_registration_count = 0
_last_received_timestamp = None
_audit_events_count = 0

# OpenTelemetry meter setup
_meter = None
_meter_provider = None
_registration_counter = None
_audit_events_counter = None
_last_received_gauge = None
_token_usage_counter = None
_operation_duration_histogram = None

# Store agent_id globally for metrics labeling
_AGENT_ID = None

def set_agent_id(agent_id: str):
    global _AGENT_ID
    _AGENT_ID = agent_id

def _setup_meter(resource: Resource = None, collector_endpoint: str = None, use_console_exporter: bool = True, exporter_protocol: str = "http"):
    """Initialize OpenTelemetry meter for agent registry metrics.
    
    Args:
        resource: OpenTelemetry resource
        collector_endpoint: OTLP collector endpoint
        use_console_exporter: Whether to also output to console
        exporter_protocol: Protocol for OTLP exporter ('http' or 'grpc')
    """
    global _meter, _meter_provider, _registration_counter, _audit_events_counter, _last_received_gauge
    
    if _meter is not None:
        return  # Already initialized
    
    try:
        # Create metric readers
        metric_readers = []
        
        # Add OTLP exporter if collector endpoint is provided
        if collector_endpoint:
            try:
                if exporter_protocol == "grpc" or (not exporter_protocol and not collector_endpoint.startswith("http")):
                    from opentelemetry.exporter.otlp.proto.grpc.metric_exporter import OTLPMetricExporter
                    otlp_exporter = OTLPMetricExporter(endpoint=collector_endpoint)
                    logger.info(f"Using OTLP gRPC metric exporter: {collector_endpoint}")
                else:
                    from opentelemetry.exporter.otlp.proto.http.metric_exporter import OTLPMetricExporter
                    otlp_exporter = OTLPMetricExporter(endpoint=collector_endpoint)
                    logger.info(f"Using OTLP HTTP metric exporter: {collector_endpoint}")
                
                otlp_reader = PeriodicExportingMetricReader(
                    otlp_exporter,
                    export_interval_millis=30000  # Export every 30 seconds
                )
                metric_readers.append(otlp_reader)
            except Exception as e:
                logger.error(f"Failed to initialize OTLP metric exporter: {e}", exc_info=True)
        
        # Add console exporter if requested or as fallback
        if use_console_exporter or not metric_readers:
            console_reader = PeriodicExportingMetricReader(
                ConsoleMetricExporter(),
                export_interval_millis=30000  # Export every 30 seconds
            )
            metric_readers.append(console_reader)
            if use_console_exporter:
                logger.info("Console metric exporter enabled")
        
        _meter_provider = MeterProvider(
            resource=resource or Resource.create({"service.name": "iagentops"}),
            metric_readers=metric_readers
        )
        metrics.set_meter_provider(_meter_provider)
        
        # Get meter
        _meter = metrics.get_meter("iagentops.agent_registry", version="0.1.0")
        
        # Create instruments
        _registration_counter = _meter.create_counter(
            name="agent.registration.success.total",
            description="Total number of successful agent registrations",
            unit="1"
        )
        
        _audit_events_counter = _meter.create_counter(
            name="agent.audit.events.total",
            description="Total number of audit events generated by agents",
            unit="1"
        )
        
        _last_received_gauge = _meter.create_observable_gauge(
            name="agent.metrics.last_received.timestamp",
            description="Timestamp of the last received metric from any agent",
            callbacks=[lambda options: [metrics.Observation(_last_received_timestamp or 0, {"agent_id": _AGENT_ID} if _AGENT_ID else {})]],
            unit="s"
        )

        global _token_usage_counter, _operation_duration_histogram
        _token_usage_counter = _meter.create_counter(
            name="gen_ai.client.token.usage",
            description="Measures number of input and output tokens used",
            unit="{token}"
        )
        _operation_duration_histogram = _meter.create_histogram(
            name="gen_ai.client.operation.duration",
            description="GenAI operation duration",
            unit="s"
        )
        
        # Register shutdown
        atexit.register(_shutdown_meter)
        
        logger.debug("OpenTelemetry meter initialized for agent registry metrics")
    except Exception as e:
        logger.error(f"Failed to initialize OpenTelemetry meter: {e}", exc_info=True)


def _shutdown_meter():
    """Gracefully shutdown meter provider."""
    global _meter_provider
    if _meter_provider:
        try:
            _meter_provider.shutdown()
            logger.debug("iAgentOps meter provider shutdown complete")
        except Exception as e:
            logger.warning(f"Error during meter shutdown: {e}")


def increment_registrations():
    """Record a successful local registration.

    Called when the SDK is initialized with an agent ID. Increments the in-memory
    registration counter and emits the OpenTelemetry counter instrument.
    """
    global _registration_count
    _registration_count += 1
    logger.debug(f"Agent registrations: {_registration_count}")
    
    # # Emit as OTel metric
    # if _registration_counter:
    #     _registration_counter.add(1)

    # Emit as OTel metric
    if _registration_counter:
        attrs = {}
        if _AGENT_ID:
            attrs["agent_id"] = _AGENT_ID
        _registration_counter.add(1, attrs)


def update_last_received():
    """Set the timestamp of the most recent LLM call.

    Stores current epoch seconds in _last_received_timestamp for observability
    and export via the observable gauge.
    """
    global _last_received_timestamp
    _last_received_timestamp = time.time()


def increment_audit_events(event_type: str = "llm_call"):
    """Record an audit event (e.g., an LLM call).

    Increments the in-memory audit event counter and emits the OpenTelemetry
    counter with an "event.type" attribute for filtering.
    """
    global _audit_events_count
    _audit_events_count += 1
    logger.debug(f"Audit event: {event_type}, total: {_audit_events_count}")
    
    # # Emit as OTel metric
    # if _audit_events_counter:
    #     _audit_events_counter.add(1, {"event.type": event_type})

    # Emit as OTel metric
    if _audit_events_counter:
        attrs = {"event.type": event_type}
        if _AGENT_ID:
            attrs["agent_id"] = _AGENT_ID
        _audit_events_counter.add(1, attrs)


def get_agent_metrics():
    """Return the current in-memory agent registry metrics as a dict.

    Returns simple primitives suitable for debugging or programmatic inspection
    (integers and epoch floats).
    """
    return {
        "agent.registration.success.total": _registration_count,
        "agent.metrics.last_received.timestamp": _last_received_timestamp,
        "agent.audit.events.total": _audit_events_count,
    }


def emit_metrics(latency_ms, provider, input_tokens=0, output_tokens=0, model=None):
    """Record an LLM call: update registry metrics and log basic stats.

    Invoked by instrumentors on each LLM request. Updates the last-received
    timestamp and audit events counter, then logs latency and token counts.
    Detailed token/latency attributes are attached to spans by the instrumentors.
    """
    # Update agent registry on every LLM call
    update_last_received()
    increment_audit_events("llm_call")

    # Emit OTel metrics
    if _token_usage_counter:
        common_attrs = {
            "model": model or "unknown", 
            "provider": provider or "unknown"
        }
        if _AGENT_ID:
            common_attrs["agent_id"] = _AGENT_ID
            
        if input_tokens > 0:
            attrs_in = common_attrs.copy()
            attrs_in["token.type"] = "input"
            _token_usage_counter.add(input_tokens, attrs_in)
            
        if output_tokens > 0:
            attrs_out = common_attrs.copy()
            attrs_out["token.type"] = "output"
            _token_usage_counter.add(output_tokens, attrs_out)

    if _operation_duration_histogram:
        attrs = {
            "model": model or "unknown", 
            "provider": provider or "unknown"
        }
        if _AGENT_ID:
            attrs["agent_id"] = _AGENT_ID
        _operation_duration_histogram.record(latency_ms / 1000.0, attrs)
    
    data = {
        "provider": provider,
        "model": model,
        "latency_ms": round(latency_ms, 2),
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "total_tokens": input_tokens + output_tokens,
    }

    if OUTPUT_FORMAT == "console":
        model_str = f" ({model})" if model else ""
        logger.info(
            f"[iAgentOps] {provider}{model_str} | "
            f"Latency: {latency_ms:.2f}ms | "
            f"Tokens: {input_tokens}→{output_tokens} ({input_tokens + output_tokens} total)"
        )
    elif OUTPUT_FORMAT == "json":
        logger.info(json.dumps(data))


def emit_agent_metrics():
    """Emit current agent registry metrics."""
    metrics = get_agent_metrics()
    logger.info(f"Agent Registry Metrics: {json.dumps(metrics)}")
